AWSTemplateFormatVersion: '2010-09-09'
Description: Fargate Cluster where Sysdig CloudVision apps are deployed
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-cloudvision-controltower.s3.amazonaws.com/sysdig/templates/sysdig_ecs_fargate_vpc.yaml
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName:
        Fn::Sub: ${AWS::StackName}
Outputs:
  ClusterName:
    Description: Cluster name for Sysdig CloudVision workload
    Value:
      Ref: ECSCluster
  VPC:
    Description: The VPC ID
    Value:
      Fn::GetAtt:
      - VPCStack
      - Outputs.VPC
  PublicSubnets:
    Description: Public Subnets
    Value:
      Fn::GetAtt:
      - VPCStack
      - Outputs.PublicSubnets
  PrivateSubnets:
    Description: Private Subnets
    Value:
      Fn::GetAtt:
      - VPCStack
      - Outputs.PrivateSubnets
