name: CI - Master

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # BETA. Rearrange once Makefile is restored
    - name: Build and Upload CFT
      run: aws s3 sync ./templates s3://cf-templates-cloudvision-controltower/sysdig/templates
      env:
        S3_BUCKET: cf-templates-cloudvision-controltower
        S3_PREFIX: sysdig/templates

    # BETA. Rearrange once Makefile is restored
    - name: Build and Uploa Onboarding package
      run: aws s3 sync ./functions/packages/onboarding s3://cf-templates-cloudvision-controltower/sysdig/functions/packages/onboarding
      env:
        S3_BUCKET: cf-templates-cloudvision-controltower
        S3_PREFIX: sysdig/functions/packages/onboarding